// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorekeeperAssistant.DataAccess;

#nullable disable

namespace StorekeeperAssistant.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250126115257_add_movementType_in_Moving")]
    partial class add_movementType_in_Moving
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StorekeeperAssistant.Domain.InventoryItems.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("StorekeeperAssistant.Domain.Movings.Moving", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArrivalWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartureWarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<int>("MovementType")
                        .HasColumnType("int")
                        .HasColumnName("MovementType");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("TransferDate");

                    b.HasKey("Id");

                    b.ToTable("Movings", (string)null);
                });

            modelBuilder.Entity("StorekeeperAssistant.Domain.Movings.MovingDetails.MovingDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MovingId");

                    b.ToTable("MovingDetails", (string)null);
                });

            modelBuilder.Entity("StorekeeperAssistant.Domain.WarehouseInventoryItems.WarehouseInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("WarehouseInventoryItems", (string)null);
                });

            modelBuilder.Entity("StorekeeperAssistant.Domain.Warehouses.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.HasKey("Id");

                    b.ToTable("Warehouses", (string)null);
                });

            modelBuilder.Entity("StorekeeperAssistant.Domain.InventoryItems.InventoryItem", b =>
                {
                    b.OwnsOne("StorekeeperAssistant.Domain.InventoryItems.InventoryItemName", "Name", b1 =>
                        {
                            b1.Property<Guid>("InventoryItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.HasKey("InventoryItemId");

                            b1.ToTable("InventoryItems");

                            b1.WithOwner()
                                .HasForeignKey("InventoryItemId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("StorekeeperAssistant.Domain.Movings.MovingDetails.MovingDetail", b =>
                {
                    b.HasOne("StorekeeperAssistant.Domain.Movings.Moving", null)
                        .WithMany("MovingDetails")
                        .HasForeignKey("MovingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("StorekeeperAssistant.Domain.Movings.MovingDetails.MovingDetailCount", "Count", b1 =>
                        {
                            b1.Property<Guid>("MovingDetailId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Count");

                            b1.HasKey("MovingDetailId");

                            b1.ToTable("MovingDetails");

                            b1.WithOwner()
                                .HasForeignKey("MovingDetailId");
                        });

                    b.Navigation("Count")
                        .IsRequired();
                });

            modelBuilder.Entity("StorekeeperAssistant.Domain.WarehouseInventoryItems.WarehouseInventoryItem", b =>
                {
                    b.OwnsOne("StorekeeperAssistant.Domain.WarehouseInventoryItems.WarehouseInventoryItemCount", "Count", b1 =>
                        {
                            b1.Property<Guid>("WarehouseInventoryItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Count");

                            b1.HasKey("WarehouseInventoryItemId");

                            b1.ToTable("WarehouseInventoryItems");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseInventoryItemId");
                        });

                    b.Navigation("Count")
                        .IsRequired();
                });

            modelBuilder.Entity("StorekeeperAssistant.Domain.Warehouses.Warehouse", b =>
                {
                    b.OwnsOne("StorekeeperAssistant.Domain.Warehouses.WarehouseName", "Name", b1 =>
                        {
                            b1.Property<Guid>("WarehouseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.HasKey("WarehouseId");

                            b1.ToTable("Warehouses");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("StorekeeperAssistant.Domain.Movings.Moving", b =>
                {
                    b.Navigation("MovingDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
