# docker-compose up -d --always-recreate-deps

version: "1.0"

name: storekeeper-assistant

services:
  storekeeper-assistant-web:
    image: ${DOCKER_REGISTRY-}storekeeper-assistant-web
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - 5000:5000
  storekeeperassistant-vue2-client:
    image: ${DOCKER_REGISTRY-}storekeeper-assistant-vue2-client
    build:
      dockerfile: Clients/StorekeeperAssistant.VueClient/Dockerfile
    ports:
      - 1315:80