export default {
  setData: "setData",
  setDepartureWarehouseId: 'setDepartureWarehouseId',
  setArrivalWarehouseId: 'setArrivalWarehouseId',
  setLoadDepartureWarehouseInventoryItems: 'setLoadDepartureWarehouseInventoryItems',
  setDepartureWarehouseInventoryItems: 'setDepartureWarehouseInventoryItems',
  setArrivalWarehouseInventoryItems: 'setArrivalWarehouseInventoryItems',
  setWarehouses: 'setWarehouses',
  setDepartureWarehouses: 'setDepartureWarehouses',
  setArrivalWarehouses: 'setArrivalWarehouses',
  setInventoryItems: 'setInventoryItems',
  setWarehouseInventoryItems: 'setWarehouseInventoryItems',
  setMovings: 'setMovings',
  setError: "setServerError",
  changeSelectOperation: "changeSelectOperation",
};
